- name: Copy Logstash Configuration File
  ansible.builtin.copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start Logstash Service
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes